### ISSUE TITLE
Wrong user? 

### ISSUE THREAD

**Issue by Philipp91** [danifr/wol-kodi#1]
On my Raspberry, the script starts the kodi binary as root. Apparently, Kodi doesn't work that way and immediately shuts down again, whereas launching the binary from a terminal or a desktop shortcut works fine. 

What am I doing wrong? Should the script itself not run as root?

**Comment by Philipp91** [comment]
It seems to work when I replace

```
subprocess.Popen(["/usr/bin/kodi"], stdout=subprocess.PIPE)
```

in `wolkodi.py:51` with

```
subprocess.Popen(["runuser", "-l", "pi", "-c", "/usr/bin/kodi"])
```

**Comment by danifr** [comment]
Hi @Philipp91,

sorry I missed your message. I'm glad you worked around it on your own.

Cheers,
Daniel.
