### ISSUE TITLE
Kodi keeps shutting down during startup

### ISSUE THREAD

**Issue by mishbieg** [danifr/wol-kodi#2]
I tried your python script and service to start kodi on a raspberry pi 3. The service seems to work but kodi shuts down right after it is started. I see the black screen trying to load it, but then it termiates and I get returned to the command line. I guess it is due to some execution rights. I also was able to write script to start kodi by a hotkey press, but it only worked by running kodi as sudo inside my sh file. Without sudo it shows the same issue an shuts down right after execution. 
Do you have any idea on how to fix that in your python script? If so, can you please update the script?
I tried a number of things, but nothing worked so far.

**Comment by danifr** [comment]
@mishbieg sorry I completely missed your comment :(
Is this still happening? I can take a look if the answer is yes.

Sorry again for my late response.

**Comment by mishbieg** [comment]
I have stoped using Kodi on the raspberry pi 3. If you want to reproduce it, you need to set it up on a pi by yourself. Otherwise I'm also fine with closing the issue.
